#!/usr/bin/env python3
"""Draw the 240x135 MothDeck boot splash and emit a 1-bit mask plus a preview PNG.

SoundCloud cover art for the moth character is not fetched here. The mark is
a high-contrast moth silhouette in the same amber-on-charcoal palette as the
Play page, sized for the Cardputer ADV ST7789.
"""

import os

from PIL import Image, ImageDraw, ImageFont

W, H = 240, 135
BG = (16, 16, 16)
INK = (255, 166, 0)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PNG = os.path.join(ROOT, "docs", "splash-moth.png")
HEADER = os.path.join(ROOT, "include", "SplashMoth.h")
FONT = "/usr/share/fonts/truetype/macos/Inter-Bold.ttf"


def moth(draw):
    cx, cy = 120, 58
    # Forewings, swept up. Hindwings sit lower and rounder.
    draw.polygon(
        [(cx - 4, cy - 2), (cx - 28, cy - 18), (cx - 78, cy - 34),
         (cx - 98, cy - 8), (cx - 86, cy + 16), (cx - 46, cy + 8)],
        fill=INK,
    )
    draw.polygon(
        [(cx + 4, cy - 2), (cx + 28, cy - 18), (cx + 78, cy - 34),
         (cx + 98, cy - 8), (cx + 86, cy + 16), (cx + 46, cy + 8)],
        fill=INK,
    )
    draw.polygon(
        [(cx - 2, cy + 6), (cx - 22, cy + 10), (cx - 70, cy + 22),
         (cx - 78, cy + 46), (cx - 40, cy + 52), (cx - 12, cy + 28)],
        fill=INK,
    )
    draw.polygon(
        [(cx + 2, cy + 6), (cx + 22, cy + 10), (cx + 70, cy + 22),
         (cx + 78, cy + 46), (cx + 40, cy + 52), (cx + 12, cy + 28)],
        fill=INK,
    )
    # Eye spots punched out of the forewings.
    draw.ellipse((cx - 62, cy - 16, cx - 40, cy + 6), fill=BG)
    draw.ellipse((cx + 40, cy - 16, cx + 62, cy + 6), fill=BG)
    draw.ellipse((cx - 56, cy - 10, cx - 46, cy), fill=INK)
    draw.ellipse((cx + 46, cy - 10, cx + 56, cy), fill=INK)
    # Body and head over the wing roots.
    draw.polygon([(cx, cy - 16), (cx - 7, cy + 4), (cx - 5, cy + 36),
                  (cx + 5, cy + 36), (cx + 7, cy + 4)], fill=INK)
    draw.ellipse((cx - 6, cy - 26, cx + 6, cy - 12), fill=INK)
    # Antennae.
    draw.line((cx - 3, cy - 22, cx - 22, cy - 44), fill=INK, width=2)
    draw.line((cx + 3, cy - 22, cx + 22, cy - 44), fill=INK, width=2)
    draw.ellipse((cx - 26, cy - 48, cx - 16, cy - 38), fill=INK)
    draw.ellipse((cx + 16, cy - 48, cx + 26, cy - 38), fill=INK)


def main():
    img = Image.new("RGB", (W, H), BG)
    draw = ImageDraw.Draw(img)
    draw.rectangle((1, 1, W - 2, H - 2), outline=INK)
    moth(draw)
    font = ImageFont.truetype(FONT, 16)
    text = "MOTHDECK"
    box = draw.textbbox((0, 0), text, font=font)
    tw = box[2] - box[0]
    draw.text(((W - tw) // 2, 108), text, font=font, fill=INK)

    os.makedirs(os.path.dirname(PNG), exist_ok=True)
    img.save(PNG)

    mask = []
    px = img.load()
    for y in range(H):
        for x in range(0, W, 8):
            byte = 0
            for bit in range(8):
                r, g, b = px[x + bit, y]
                if r > 80:
                    byte |= 0x80 >> bit
            mask.append(byte)

    lines = [
        "#pragma once",
        "// Generated by tools/make_splash.py. 240x135, 1 bit per pixel, MSB first.",
        "// Amber ink on the Play-page background. Do not edit the bytes by hand.",
        "static const int kSplashW = 240;",
        "static const int kSplashH = 135;",
        "static const uint8_t kSplashMoth[] = {",
    ]
    for i in range(0, len(mask), 15):
        chunk = mask[i:i + 15]
        lines.append("  " + ", ".join("0x%02x" % b for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    with open(HEADER, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("wrote", PNG, "and", HEADER, "bytes", len(mask))


if __name__ == "__main__":
    main()
